In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('house_data.csv')
df=df.dropna()

In [3]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7.129301e+09  20141013T000000  221900.0       3.0       1.00       1180.0   
1  6.414100e+09  20141209T000000  538000.0       3.0       2.25       2570.0   
2  5.631500e+09  20150225T000000  180000.0       2.0       1.00        770.0   
3  2.487201e+09  20141209T000000  604000.0       4.0       3.00       1960.0   
4  1.954401e+09  20150218T000000  510000.0       3.0       2.00       1680.0   

   sqft_lot  floors  
0    5650.0     1.0  
1    7242.0     2.0  
2   10000.0     1.0  
3    5000.0     1.0  
4    8080.0     1.0

In [4]:
df.head(8)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7.129301e+09  20141013T000000   221900.0       3.0       1.00       1180.0   
1  6.414100e+09  20141209T000000   538000.0       3.0       2.25       2570.0   
2  5.631500e+09  20150225T000000   180000.0       2.0       1.00        770.0   
3  2.487201e+09  20141209T000000   604000.0       4.0       3.00       1960.0   
4  1.954401e+09  20150218T000000   510000.0       3.0       2.00       1680.0   
5  7.237550e+09  20140512T000000  1230000.0       4.0       4.50       5420.0   
6  1.321400e+09  20140627T000000   257500.0       3.0       2.25       1715.0   
7  2.008000e+09  20150115T000000   291850.0       3.0       1.50       1060.0   

   sqft_lot  floors  
0    5650.0     1.0  
1    7242.0     2.0  
2   10000.0     1.0  
3    5000.0     1.0  
4    8080.0     1.0  
5  101930.0     1.0  
6    6819.0     2.0  
7    9711.0     1.0

In [5]:
df.shape

(99, 8)

In [6]:
df.tail()

id             date     price  bedrooms  bathrooms  sqft_living  \
94  6.021502e+09  20141223T000000  700000.0       3.0       1.50       1580.0   
95  1.483301e+09  20140908T000000  905000.0       4.0       2.50       3300.0   
96  3.422049e+09  20150330T000000  247500.0       3.0       1.75       1960.0   
97  1.099611e+09  20140912T000000  199000.0       4.0       1.50       1160.0   
98  7.220791e+08  20140711T000000  314000.0       3.0       1.75       1810.0   

    sqft_lot  floors  
94    5000.0     1.0  
95   10250.0     1.0  
96   15681.0     1.0  
97    6400.0     1.0  
98   41800.0     1.0

In [7]:
df.tail(9)

id             date      price  bedrooms  bathrooms  \
90  2.791500e+09  20140522T000000   243500.0       4.0       2.50   
91  5.036300e+09  20150311T000000  1100000.0       5.0       2.75   
92  4.168000e+09  20150226T000000   153000.0       3.0       1.00   
93  6.021502e+09  20140725T000000   430000.0       3.0       1.50   
94  6.021502e+09  20141223T000000   700000.0       3.0       1.50   
95  1.483301e+09  20140908T000000   905000.0       4.0       2.50   
96  3.422049e+09  20150330T000000   247500.0       3.0       1.75   
97  1.099611e+09  20140912T000000   199000.0       4.0       1.50   
98  7.220791e+08  20140711T000000   314000.0       3.0       1.75   

    sqft_living  sqft_lot  floors  
90       1980.0    7403.0     2.0  
91       3520.0    6353.0     2.0  
92       1200.0   10500.0     1.0  
93       1580.0    5000.0     1.0  
94       1580.0    5000.0     1.0  
95       3300.0   10250.0     1.0  
96       1960.0   15681.0     1.0  
97       1160.0    6400.0     1.0  
98       1810.0   41800.0     1.0

In [8]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors'],
      dtype='object')

In [9]:
df.size

792

In [10]:
df.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
            85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
           dtype='int64')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 98
Data columns (total 8 columns):
id             99 non-null float64
date           99 non-null object
price          99 non-null float64
bedrooms       99 non-null float64
bathrooms      99 non-null float64
sqft_living    99 non-null float64
sqft_lot       99 non-null float64
floors         99 non-null float64
dtypes: float64(7), object(1)
memory usage: 7.0+ KB


In [12]:
df.describe()

id         price   bedrooms  bathrooms  sqft_living  \
count  9.900000e+01  9.900000e+01  99.000000  99.000000    99.000000   
mean   4.664620e+09  5.200763e+05   3.404040   1.989899  2086.383838   
std    2.935212e+09  3.061939e+05   0.794358   0.729236   864.592421   
min    1.600040e+07  1.530000e+05   2.000000   1.000000   770.000000   
25%    1.914950e+09  3.070000e+05   3.000000   1.500000  1410.000000   
50%    4.036801e+09  4.300000e+05   3.000000   2.000000  1900.000000   
75%    7.337325e+09  6.562500e+05   4.000000   2.500000  2570.000000   
max    9.822700e+09  2.000000e+06   5.000000   4.500000  5420.000000   

            sqft_lot     floors  
count      99.000000  99.000000  
mean    11478.818182   1.464646  
std     14655.249813   0.511363  
min      1044.000000   1.000000  
25%      5000.000000   1.000000  
50%      6720.000000   1.500000  
75%      9823.000000   2.000000  
max    101930.000000   3.000000

In [13]:
df

id             date     price  bedrooms  bathrooms  sqft_living  \
0   7.129301e+09  20141013T000000  221900.0       3.0       1.00       1180.0   
1   6.414100e+09  20141209T000000  538000.0       3.0       2.25       2570.0   
2   5.631500e+09  20150225T000000  180000.0       2.0       1.00        770.0   
3   2.487201e+09  20141209T000000  604000.0       4.0       3.00       1960.0   
4   1.954401e+09  20150218T000000  510000.0       3.0       2.00       1680.0   
..           ...              ...       ...       ...        ...          ...   
94  6.021502e+09  20141223T000000  700000.0       3.0       1.50       1580.0   
95  1.483301e+09  20140908T000000  905000.0       4.0       2.50       3300.0   
96  3.422049e+09  20150330T000000  247500.0       3.0       1.75       1960.0   
97  1.099611e+09  20140912T000000  199000.0       4.0       1.50       1160.0   
98  7.220791e+08  20140711T000000  314000.0       3.0       1.75       1810.0   

    sqft_lot  floors  
0     5650.0     1.0  
1     7242.0     2.0  
2    10000.0     1.0  
3     5000.0     1.0  
4     8080.0     1.0  
..       ...     ...  
94    5000.0     1.0  
95   10250.0     1.0  
96   15681.0     1.0  
97    6400.0     1.0  
98   41800.0     1.0  

[99 rows x 8 columns]

In [14]:
df['price']

0     221900.0
1     538000.0
2     180000.0
3     604000.0
4     510000.0
        ...   
94    700000.0
95    905000.0
96    247500.0
97    199000.0
98    314000.0
Name: price, Length: 99, dtype: float64

In [15]:
df[['id','price']]

id     price
0   7.129301e+09  221900.0
1   6.414100e+09  538000.0
2   5.631500e+09  180000.0
3   2.487201e+09  604000.0
4   1.954401e+09  510000.0
..           ...       ...
94  6.021502e+09  700000.0
95  1.483301e+09  905000.0
96  3.422049e+09  247500.0
97  1.099611e+09  199000.0
98  7.220791e+08  314000.0

[99 rows x 2 columns]

In [16]:
df.price.max()

2000000.0

In [17]:
df.price.min()

153000.0

In [18]:
df.price.std()

306193.9075957721

In [19]:
df.price.mean()

520076.31313131313

In [20]:
df.id.unique()

array([7.12930052e+09, 6.41410019e+09, 5.63150040e+09, 2.48720088e+09,
       1.95440051e+09, 7.23755031e+09, 1.32140006e+09, 2.00800027e+09,
       2.41460013e+09, 3.79350016e+09, 1.73680052e+09, 9.21290026e+09,
       1.14101516e+08, 6.05465007e+09, 1.17500057e+09, 9.29730006e+09,
       1.87550006e+09, 6.86520014e+09, 1.60003970e+07, 7.98320006e+09,
       6.30050088e+09, 2.52404918e+09, 7.13797034e+09, 8.09140020e+09,
       3.81470020e+09, 1.20200020e+09, 1.79450038e+09, 3.30370038e+09,
       5.10140249e+09, 1.87310039e+09, 8.56275032e+09, 2.42603931e+09,
       4.61000390e+08, 7.58920019e+09, 7.95508027e+09, 9.54720518e+09,
       9.43530003e+09, 2.76800040e+09, 7.89550007e+09, 2.07850032e+09,
       5.54770027e+09, 7.76620001e+09, 7.20322040e+09, 9.27020016e+09,
       1.43270123e+09, 8.03535032e+09, 8.94520083e+09, 4.17830031e+09,
       9.21540010e+09, 8.22039084e+08, 5.24560010e+09, 7.23130012e+09,
       7.51850599e+09, 3.62603927e+09, 4.21740120e+09, 9.82270030e+09,
      

In [21]:
df.price.count()

99

In [22]:
df.id.isnull().sum()

0

In [23]:
df.bedrooms.sum()

337.0

In [24]:
df.bedrooms.value_counts()

3.0    51
4.0    29
5.0    10
2.0     9
Name: bedrooms, dtype: int64

In [25]:
df[df['price']<=250000]

id             date     price  bedrooms  bathrooms  sqft_living  \
0   7.129301e+09  20141013T000000  221900.0       3.0       1.00       1180.0   
2   5.631500e+09  20150225T000000  180000.0       2.0       1.00        770.0   
8   2.414600e+09  20150415T000000  229500.0       3.0       1.00       1780.0   
18  1.600040e+07  20141205T000000  189000.0       2.0       1.00       1200.0   
19  7.983200e+09  20150424T000000  230000.0       3.0       1.00       1250.0   
25  1.202000e+09  20141103T000000  233000.0       3.0       2.00       1710.0   
38  7.895500e+09  20150213T000000  240000.0       4.0       1.00       1220.0   
46  8.945201e+09  20150325T000000  210490.0       3.0       1.00        990.0   
50  5.245600e+09  20140916T000000  228000.0       3.0       1.00       1190.0   
68  1.274500e+09  20140825T000000  204000.0       3.0       1.00       1000.0   
88  1.332700e+09  20140519T000000  215000.0       2.0       2.25       1610.0   
90  2.791500e+09  20140522T000000  243500.0       4.0       2.50       1980.0   
92  4.168000e+09  20150226T000000  153000.0       3.0       1.00       1200.0   
96  3.422049e+09  20150330T000000  247500.0       3.0       1.75       1960.0   
97  1.099611e+09  20140912T000000  199000.0       4.0       1.50       1160.0   

    sqft_lot  floors  
0     5650.0     1.0  
2    10000.0     1.0  
8     7470.0     1.0  
18    9850.0     1.0  
19    9774.0     1.0  
25    4697.0     1.5  
38    8075.0     1.0  
46    8528.0     1.0  
50    9199.0     1.0  
68   12070.0     1.0  
88    2040.0     2.0  
90    7403.0     2.0  
92   10500.0     1.0  
96   15681.0     1.0  
97    6400.0     1.0

In [26]:
df[['bedrooms','bathrooms']][df['price']==df.price.max()]

bedrooms  bathrooms
21       3.0       2.75

In [27]:
df.set_index('id',inplace=True)
df.head()

date     price  bedrooms  bathrooms  sqft_living  \
id                                                                          
7.129301e+09  20141013T000000  221900.0       3.0       1.00       1180.0   
6.414100e+09  20141209T000000  538000.0       3.0       2.25       2570.0   
5.631500e+09  20150225T000000  180000.0       2.0       1.00        770.0   
2.487201e+09  20141209T000000  604000.0       4.0       3.00       1960.0   
1.954401e+09  20150218T000000  510000.0       3.0       2.00       1680.0   

              sqft_lot  floors  
id                              
7.129301e+09    5650.0     1.0  
6.414100e+09    7242.0     2.0  
5.631500e+09   10000.0     1.0  
2.487201e+09    5000.0     1.0  
1.954401e+09    8080.0     1.0

In [28]:
df.fillna(0,inplace=True)

In [29]:
df.loc[5631500400]

date           20150225T000000
price                   180000
bedrooms                     2
bathrooms                    1
sqft_living                770
sqft_lot                 10000
floors                       1
Name: 5631500400.0, dtype: object

In [30]:
df.reset_index(inplace=True)

In [31]:
dummies=pd.get_dummies(df.bedrooms)

In [32]:
df=pd.concat([df,dummies],axis='columns')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7.129301e+09  20141013T000000  221900.0       3.0       1.00       1180.0   
1  6.414100e+09  20141209T000000  538000.0       3.0       2.25       2570.0   
2  5.631500e+09  20150225T000000  180000.0       2.0       1.00        770.0   
3  2.487201e+09  20141209T000000  604000.0       4.0       3.00       1960.0   
4  1.954401e+09  20150218T000000  510000.0       3.0       2.00       1680.0   

   sqft_lot  floors  2.0  3.0  4.0  5.0  
0    5650.0     1.0    0    1    0    0  
1    7242.0     2.0    0    1    0    0  
2   10000.0     1.0    1    0    0    0  
3    5000.0     1.0    0    0    1    0  
4    8080.0     1.0    0    1    0    0

In [33]:
train=df.sample(frac=0.75,random_state=1)
test=df.drop(train.index)

In [34]:
train

id             date     price  bedrooms  bathrooms  sqft_living  \
92  4.168000e+09  20150226T000000  153000.0       3.0       1.00       1200.0   
83  1.523059e+09  20150128T000000  356000.0       3.0       1.50       1680.0   
32  4.610004e+08  20140624T000000  687500.0       4.0       1.75       2330.0   
80  5.104520e+09  20141202T000000  390000.0       3.0       2.50       2350.0   
78  6.300000e+09  20140609T000000  410000.0       3.0       1.00       1410.0   
..           ...              ...       ...       ...        ...          ...   
57  2.799801e+09  20150407T000000  301000.0       3.0       2.50       2420.0   
22  7.137970e+09  20140703T000000  285000.0       5.0       2.50       2270.0   
61  9.558200e+09  20140828T000000  289000.0       3.0       1.75       1260.0   
63  9.528103e+09  20141207T000000  549000.0       3.0       1.75       1540.0   
7   2.008000e+09  20150115T000000  291850.0       3.0       1.50       1060.0   

    sqft_lot  floors  2.0  3.0  4.0  5.0  
92   10500.0     1.0    0    1    0    0  
83    8712.0     1.0    0    1    0    0  
32    5000.0     1.5    0    0    1    0  
80    5100.0     2.0    0    1    0    0  
78    5060.0     1.0    0    1    0    0  
..       ...     ...  ...  ...  ...  ...  
57    4750.0     2.0    0    1    0    0  
22    6300.0     2.0    0    0    0    1  
61    8400.0     1.0    0    1    0    0  
63    1044.0     3.0    0    1    0    0  
7     9711.0     1.0    0    1    0    0  

[74 rows x 12 columns]

In [35]:
test.count()

id             25
date           25
price          25
bedrooms       25
bathrooms      25
sqft_living    25
sqft_lot       25
floors         25
2.0            25
3.0            25
4.0            25
5.0            25
dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
x=np.array(df['price'])
y=np.array(df['bedrooms'])
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.75)

In [37]:
X_test,y_test

(array([ 940000.,  861990.,  720000.,  488000.,  625000.,  349000.,
         530000.,  329000.,  233000.,  510000.,  325000.,  189000.,
         550000.,  920000.,  937000.,  905000.,  243500.,  719000.,
         430000.,  385000.,  204000.,  323000.,  240000.,  605000.,
         289000.,  505000.,  309000.,  257500.,  221900.,  430000.,
         360000.,  585000.,  360000.,  291850.,  775000.,  650000.,
         461000.,  685000.,  314000.,  485000.,  310000.,  832500.,
         292500.,  322500.,  700000.,  395000.,  425000.,  696000.,
         549000.,  480000.,  400000.,  287000., 2000000.,  252700.,
         247500.,  180000.,  228000.,  604000.,  600000., 1100000.,
         356000.,  450000., 1330000.,  317625.,  535000.,  335000.,
        1230000.,  215000.,  355000.,  951000.,  199000.,  285000.,
         662500.,  229500.,  390000.]),
 array([3., 5., 4., 3., 4., 3., 5., 3., 3., 3., 3., 2., 4., 5., 3., 4., 4.,
        4., 3., 4., 3., 3., 4., 4., 3., 3., 3., 3., 3., 4., 4., 2., 

In [38]:
X_train,y_train

(array([ 345000.,  640000., 1350000.,  571000.,  785000., 1040000.,
         580500.,  687500.,  305000.,  538000.,  410000.,  301000.,
         380000.,  280000.,  153000.,  468000.,  667000.,  210490.,
         885000.,  650000.,  315000.,  230000.,  975000.,  438000.]),
 array([5., 4., 3., 4., 4., 5., 3., 4., 5., 3., 3., 3., 4., 2., 3., 2., 3.,
        3., 4., 4., 3., 3., 4., 3.]))